apiVersion: v1
kind: Pod
metadata:
  name: mybusybox
  labels:
    app: busybox
spec:
  volumes:
  - name: pvstorage
    persistentVolumeClaim:
      claimName: busybox-pv-claim
  containers:
  - image: docker.io/indk00r/my-repo:1.1
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: mybusybox
  restartPolicy: Always
  volumeMounts:
    - mountPath: "/mnt"
      name: pvstorage
