apiVersion: v1
kind: Pod
metadata:
  name: mybusybox
  labels:
    app: busybox
spec:
  containers:
  - image: docker.io/indk00r/my-repo:1.1
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: mybusybox
  restartPolicy: Always
